// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3LGYksWN8ZBpkTSV8WBDUcwV1ZRp5BFs',
    appId: '1:261444940819:web:750d93e819b4cfe56c3be6',
    messagingSenderId: '261444940819',
    projectId: 'pet-recorder',
    authDomain: 'pet-recorder.firebaseapp.com',
    storageBucket: 'pet-recorder.appspot.com',
    measurementId: 'G-P4XY80DYE2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUeO1wXRrobhUmHUXqfOTqv9cI9em0L1E',
    appId: '1:261444940819:android:9e138dc6158126676c3be6',
    messagingSenderId: '261444940819',
    projectId: 'pet-recorder',
    storageBucket: 'pet-recorder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn4jLCP7Q5oqFXC69U3SqMFZnhOfJXxpE',
    appId: '1:261444940819:ios:e1bd8424a412f65d6c3be6',
    messagingSenderId: '261444940819',
    projectId: 'pet-recorder',
    storageBucket: 'pet-recorder.appspot.com',
    iosBundleId: 'com.example.petRecorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn4jLCP7Q5oqFXC69U3SqMFZnhOfJXxpE',
    appId: '1:261444940819:ios:67c9ec3d62b1b2eb6c3be6',
    messagingSenderId: '261444940819',
    projectId: 'pet-recorder',
    storageBucket: 'pet-recorder.appspot.com',
    iosBundleId: 'com.example.petRecorder.RunnerTests',
  );
}
